[build]
  base = "docs/"
  command = "make deploy-preview"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF . ../examples ../helm-chart/crds ../api"

[context.production]
  command = "make all"

[context.docs-development]
  command = "make all-dev"

[context.docs-staging]
  command = "make all-staging"

[context.branch-deploy]
  command = "make deploy-preview"

[context.deploy-preview]
  command = "make deploy-preview"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://docs.nginx.com"

[[redirects]]
  from = "/"
  to = "/nginx-service-mesh/"
  status = 301
  force = true

[[redirects]]
  from = "/nginx-service-mesh/robots.txt"
  to = "https://docs.nginx.com/robots.txt"
  status = 301
  force = true

[[redirects]]
  from = "/nginx-service-mesh/*"
  to = "/nginx-service-mesh/404.html"
  status = 404
